services:
  postgres:
    image: postgres:16-alpine
    container_name: bookline-postgres-dev
    environment:
      POSTGRES_DB: bookline_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: bookline-redis-dev
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:v1.15
    container_name: bookline-mailpit-dev
    ports:
      - "1026:1025"
      - "8026:8025"
