<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookline.Application\Bookline.Application.csproj" />
    <ProjectReference Include="..\Bookline.Infrastructure\Bookline.Infrastructure.csproj" />
  </ItemGroup>
</Project>
